<script lang="ts">
    import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "$lib/components/ui/card";
    import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "$lib/components/ui/table";
    import type { PageData } from './$types';

    interface Props {
        data: PageData;
    }

    let { data }: Props = $props();

    function formatDate(dateString: string) {
        const date = new Date(dateString);
        return new Intl.DateTimeFormat('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric'
        }).format(date);
    }
</script>

<div class="container mx-auto p-6 space-y-6">
    <h1 class="text-3xl font-bold mb-8">Id Card Gen Dashboard</h1>

    <!-- Overview Stats -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card>
            <CardHeader>
                <CardTitle>Total Templates</CardTitle>
                <CardDescription>Active templates across all orgs</CardDescription>
            </CardHeader>
            <CardContent>
                <p class="text-4xl font-bold">{data.stats.totalTemplates}</p>
            </CardContent>
        </Card>

        <Card>
            <CardHeader>
                <CardTitle>Total ID Cards</CardTitle>
                <CardDescription>Generated ID cards</CardDescription>
            </CardHeader>
            <CardContent>
                <p class="text-4xl font-bold">{data.stats.totalIdCards}</p>
            </CardContent>
        </Card>

        <Card>
            <CardHeader>
                <CardTitle>Organizations</CardTitle>
                <CardDescription>Active organizations</CardDescription>
            </CardHeader>
            <CardContent>
                <p class="text-4xl font-bold">{data.stats.totalOrganizations}</p>
            </CardContent>
        </Card>

        <Card>
            <CardHeader>
                <CardTitle>Total Users</CardTitle>
                <CardDescription>Registered users</CardDescription>
            </CardHeader>
            <CardContent>
                <p class="text-4xl font-bold">{data.stats.totalUsers}</p>
            </CardContent>
        </Card>
    </div>

    <!-- User Distribution -->
    <Card>
        <CardHeader>
            <CardTitle>User Distribution</CardTitle>
            <CardDescription>Users by role</CardDescription>
        </CardHeader>
        <CardContent>
            <div class="grid grid-cols-3 gap-4">
                <div class="text-center p-4 rounded-lg bg-primary/10">
                    <p class="text-2xl font-bold">{data.stats.usersByRole.superAdmin}</p>
                    <p class="text-sm text-muted-foreground">Super Admins</p>
                </div>
                <div class="text-center p-4 rounded-lg bg-primary/10">
                    <p class="text-2xl font-bold">{data.stats.usersByRole.orgAdmin}</p>
                    <p class="text-sm text-muted-foreground">Org Admins</p>
                </div>
                <div class="text-center p-4 rounded-lg bg-primary/10">
                    <p class="text-2xl font-bold">{data.stats.usersByRole.user}</p>
                    <p class="text-sm text-muted-foreground">Regular Users</p>
                </div>
            </div>
        </CardContent>
    </Card>

    <!-- Organization Stats -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Templates per Organization -->
        <Card>
            <CardHeader>
                <CardTitle>Templates per Organization</CardTitle>
                <CardDescription>Number of templates created by each org</CardDescription>
            </CardHeader>
            <CardContent>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Organization</TableHead>
                            <TableHead class="text-right">Templates</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {#each data.stats.templatesPerOrg as { orgName, count }}
                            <TableRow>
                                <TableCell>{orgName}</TableCell>
                                <TableCell class="text-right">{count}</TableCell>
                            </TableRow>
                        {/each}
                    </TableBody>
                </Table>
            </CardContent>
        </Card>

        <!-- ID Cards per Organization -->
        <Card>
            <CardHeader>
                <CardTitle>ID Cards per Organization</CardTitle>
                <CardDescription>Number of ID cards generated by each org</CardDescription>
            </CardHeader>
            <CardContent>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Organization</TableHead>
                            <TableHead class="text-right">ID Cards</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {#each data.stats.idCardsPerOrg as { orgName, count }}
                            <TableRow>
                                <TableCell>{orgName}</TableCell>
                                <TableCell class="text-right">{count}</TableCell>
                            </TableRow>
                        {/each}
                    </TableBody>
                </Table>
            </CardContent>
        </Card>
    </div>

    <!-- Recent Activity -->
    <Card>
        <CardHeader>
            <CardTitle>Recent ID Cards</CardTitle>
            <CardDescription>Latest ID cards generated across all organizations</CardDescription>
        </CardHeader>
        <CardContent>
            <Table>
                <TableHeader>
                    <TableRow>
                        <TableHead>Organization</TableHead>
                        <TableHead>Template</TableHead>
                        <TableHead>Created At</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {#each data.idcards.slice(0, 5) as idcard}
                        <TableRow>
                            <TableCell>
                                {data.organizations.find(org => org.id === idcard.org_id)?.name || 'Unknown'}
                            </TableCell>
                            <TableCell>
                                {data.templates.find(t => t.id === idcard.template_id)?.name || 'Unknown'}
                            </TableCell>
                            <TableCell>{formatDate(idcard.created_at)}</TableCell>
                        </TableRow>
                    {/each}
                </TableBody>
            </Table>
        </CardContent>
    </Card>
</div>
