/**
 * Stock Constants — Static seed data for inventory items.
 * Separated from stock.svelte.ts to reduce file size.
 */

export type StockCategory = 'Meats' | 'Sides' | 'Dishes' | 'Drinks';
export type MeatProtein = 'beef' | 'pork' | 'chicken' | 'other';

/** Infers protein type from a menuItemId string (beef/pork/chicken check order matters). */
export function getProteinType(menuItemId: string): MeatProtein | undefined {
	if (menuItemId.includes('beef')) return 'beef';
	if (menuItemId.includes('pork')) return 'pork';
	if (menuItemId.includes('chicken')) return 'chicken';
	return undefined;
}

export const STOCK_ITEMS_LIST: {
	menuItemId: string;
	name: string;
	category: StockCategory;
	proteinType?: MeatProtein;
	locationId: string;
	unit: string;
	minLevel: number;
}[] = [
	// ── QC Branch Stock ──────────────────────────────────────────────────────
	{ menuItemId: 'meat-pork-bone-in',   name: 'Pork Bone-In',               category: 'Meats', proteinType: 'pork', locationId: 'qc', unit: 'g',        minLevel: 5000 },
	{ menuItemId: 'meat-pork-bone-out',  name: 'Pork Bone-Out',              category: 'Meats', proteinType: 'pork', locationId: 'qc', unit: 'g',        minLevel: 5000 },
	{ menuItemId: 'meat-pork-sliced',    name: 'Sliced Pork',                category: 'Meats', proteinType: 'pork', locationId: 'qc', unit: 'g',        minLevel: 5000 },
	{ menuItemId: 'meat-pork-bones',     name: 'Pork Bones',                 category: 'Meats', proteinType: 'pork', locationId: 'qc', unit: 'g',        minLevel: 2000 },
	{ menuItemId: 'meat-pork-trimmings', name: 'Pork Trimmings',             category: 'Meats', proteinType: 'pork', locationId: 'qc', unit: 'g',        minLevel: 1000 },
	{ menuItemId: 'meat-beef-bone-in',   name: 'Beef Bone-In',               category: 'Meats', proteinType: 'beef', locationId: 'qc', unit: 'g',        minLevel: 3000 },
	{ menuItemId: 'meat-beef-bone-out',  name: 'Beef Bone-Out',              category: 'Meats', proteinType: 'beef', locationId: 'qc', unit: 'g',        minLevel: 3000 },
	{ menuItemId: 'meat-beef-sliced',    name: 'Sliced Beef',                category: 'Meats', proteinType: 'beef', locationId: 'qc', unit: 'g',        minLevel: 3000 },
	{ menuItemId: 'meat-beef-bones',     name: 'Beef Bones',                 category: 'Meats', proteinType: 'beef', locationId: 'qc', unit: 'g',        minLevel: 1000 },
	{ menuItemId: 'meat-beef-trimmings', name: 'Beef Trimmings',             category: 'Meats', proteinType: 'beef', locationId: 'qc', unit: 'g',        minLevel: 500  },
	{ menuItemId: 'meat-chicken-wing',   name: 'Chicken Wing',               category: 'Meats', proteinType: 'chicken', locationId: 'qc', unit: 'g',        minLevel: 2000 },
	{ menuItemId: 'meat-chicken-leg',    name: 'Chicken Leg',                category: 'Meats', proteinType: 'chicken', locationId: 'qc', unit: 'g',        minLevel: 2000 },
	{ menuItemId: 'side-kimchi',         name: 'Kimchi',                     category: 'Sides',  locationId: 'qc', unit: 'portions', minLevel: 10   },
	{ menuItemId: 'side-rice',           name: 'Steamed Rice',               category: 'Sides',  locationId: 'qc', unit: 'portions', minLevel: 15   },
	{ menuItemId: 'drink-soju',          name: 'Soju (Original)',            category: 'Drinks', locationId: 'qc', unit: 'bottles',  minLevel: 12   },

	// ── Additional QC stock ───────────────────────────────────────────────────
	{ menuItemId: 'sides-lettuce',                         name: 'Lettuce',                   category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-perilla-leaves-kkaennip',         name: 'Perilla Leaves (Kkaennip)', category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-garlic-whole-cloves',             name: 'Garlic (Whole Cloves)',     category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-garlic-sliced',                   name: 'Garlic (Sliced)',           category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-green-onions-scallions',          name: 'Green Onions / Scallions',  category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-jalape-o-green-chilies',          name: 'Jalapeño / Green Chilies',  category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-white-yellow-onions',             name: 'White/Yellow Onions',       category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-korean-radish-mu',                name: 'Korean Radish (Mu)',        category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-enoki-mushrooms',                 name: 'Enoki Mushrooms',           category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-button-mushrooms',                name: 'Button Mushrooms',          category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-corn',                            name: 'Corn',                      category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-baguio-pechay',                   name: 'Baguio Pechay',             category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-squash',                          name: 'Squash',                    category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-baechu-kimchi',                   name: 'Baechu Kimchi',             category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-kkakdugi',                        name: 'Kkakdugi',                  category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-kongnamul-muchim',                name: 'Kongnamul-muchim',          category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-oi-muchim',                       name: 'Oi Muchim',                 category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-pickled-white-onions',            name: 'Pickled White Onions',      category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-pickled-daikon-radish',           name: 'Pickled Daikon Radish',     category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-eomuk-bokkeum',                   name: 'Eomuk Bokkeum',             category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-japchae',                         name: 'Japchae',                   category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-gamja-jorim',                     name: 'Gamja Jorim',               category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-gyeran-jjim',                     name: 'Gyeran-jjim',               category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-pajeon',                          name: 'Pajeon',                    category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-gamja-salad',                     name: 'Gamja Salad',               category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-cheesy-tteokbokki',               name: 'Cheesy Tteokbokki',         category: 'Sides',     locationId: 'qc',      unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-gochujang',                       name: 'Gochujang',                 category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-doenjang',                        name: 'Doenjang',                  category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-gochugaru-coarse',                name: 'Gochugaru (Coarse)',        category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-gochugaru-fine',                  name: 'Gochugaru (Fine)',          category: 'Sides',     locationId: 'qc',      unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-jin-ganjang-dark-soy-sauce',      name: 'Jin-ganjang (Dark Soy Sauce)', category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-guk-ganjang-soup-soy-sauce',      name: 'Guk-ganjang (Soup Soy Sauce)', category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-yangjo-ganjang-brewed-soy',       name: 'Yangjo-ganjang (Brewed Soy)', category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-toasted-sesame-oil',              name: 'Toasted Sesame Oil',        category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-mulyeot-corn-rice-syrup',         name: 'Mulyeot (Corn/Rice Syrup)', category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-mirin-rice-wine',                 name: 'Mirin / Rice Wine',         category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-aekjeot-fish-sauce',              name: 'Aekjeot (Fish Sauce)',      category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-dasida-beef-stock-powder',        name: 'Dasida (Beef Stock Powder)', category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-mayonnaise',                      name: 'Mayonnaise',                category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-ssamjang',                        name: 'Ssamjang',                  category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 1000   },
	{ menuItemId: 'sides-sogeumjang',                      name: 'Sogeumjang',                category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 1000   },
	{ menuItemId: 'sides-cheese-sauce',                    name: 'Cheese Sauce',              category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 1000   },
	{ menuItemId: 'sides-wasabi-soy',                      name: 'Wasabi Soy',                category: 'Sides',     locationId: 'qc',      unit: 'ml',         minLevel: 1000   },
	{ menuItemId: 'drinks-original-soju',                  name: 'Original Soju',             category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-flavored-soju-grapefruit',       name: 'Flavored Soju - Grapefruit', category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-flavored-soju-green-grape',      name: 'Flavored Soju - Green Grape', category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-flavored-soju-plum',             name: 'Flavored Soju - Plum',      category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-flavored-soju-strawberry',       name: 'Flavored Soju - Strawberry', category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-makgeolli',                      name: 'Makgeolli',                 category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-san-miguel-pilsen',              name: 'San Miguel Pilsen',         category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-san-miguel-light',               name: 'San Miguel Light',          category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-red-horse',                      name: 'Red Horse',                 category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-cass',                           name: 'Cass',                      category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-hite',                           name: 'Hite',                      category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-ob',                             name: 'OB',                        category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-taedonggang',                    name: 'Taedonggang',               category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-coca-cola',                      name: 'Coca-Cola',                 category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-sprite',                         name: 'Sprite',                    category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-coke-zero',                      name: 'Coke Zero',                 category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-chilsung-cider',                 name: 'Chilsung Cider',            category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-iced-red-tea',                   name: 'Iced Red Tea',              category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-barley-tea-boricha',             name: 'Barley Tea (Boricha)',      category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-lemonade',                       name: 'Lemonade',                  category: 'Drinks',    locationId: 'qc',      unit: 'bottles',    minLevel: 24     },

	// ── Makati Branch Stock ───────────────────────────────────────────────────
	{ menuItemId: 'meat-pork-bone-in',   name: 'Pork Bone-In',               category: 'Meats', proteinType: 'pork', locationId: 'mkti', unit: 'g',        minLevel: 5000 },
	{ menuItemId: 'meat-pork-bone-out',  name: 'Pork Bone-Out',              category: 'Meats', proteinType: 'pork', locationId: 'mkti', unit: 'g',        minLevel: 5000 },
	{ menuItemId: 'meat-pork-sliced',    name: 'Sliced Pork',                category: 'Meats', proteinType: 'pork', locationId: 'mkti', unit: 'g',        minLevel: 5000 },
	{ menuItemId: 'meat-pork-bones',     name: 'Pork Bones',                 category: 'Meats', proteinType: 'pork', locationId: 'mkti', unit: 'g',        minLevel: 2000 },
	{ menuItemId: 'meat-pork-trimmings', name: 'Pork Trimmings',             category: 'Meats', proteinType: 'pork', locationId: 'mkti', unit: 'g',        minLevel: 1000 },
	{ menuItemId: 'meat-beef-bone-in',   name: 'Beef Bone-In',               category: 'Meats', proteinType: 'beef', locationId: 'mkti', unit: 'g',        minLevel: 3000 },
	{ menuItemId: 'meat-beef-bone-out',  name: 'Beef Bone-Out',              category: 'Meats', proteinType: 'beef', locationId: 'mkti', unit: 'g',        minLevel: 3000 },
	{ menuItemId: 'meat-beef-sliced',    name: 'Sliced Beef',                category: 'Meats', proteinType: 'beef', locationId: 'mkti', unit: 'g',        minLevel: 3000 },
	{ menuItemId: 'meat-beef-bones',     name: 'Beef Bones',                 category: 'Meats', proteinType: 'beef', locationId: 'mkti', unit: 'g',        minLevel: 1000 },
	{ menuItemId: 'meat-beef-trimmings', name: 'Beef Trimmings',             category: 'Meats', proteinType: 'beef', locationId: 'mkti', unit: 'g',        minLevel: 500  },
	{ menuItemId: 'meat-chicken-wing',   name: 'Chicken Wing',               category: 'Meats', proteinType: 'chicken', locationId: 'mkti', unit: 'g',        minLevel: 2000 },
	{ menuItemId: 'meat-chicken-leg',    name: 'Chicken Leg',                category: 'Meats', proteinType: 'chicken', locationId: 'mkti', unit: 'g',        minLevel: 2000 },
	{ menuItemId: 'drink-soju',          name: 'Soju (Original)',            category: 'Drinks', locationId: 'mkti', unit: 'bottles',  minLevel: 12   },

	// ── Additional Makati stock ───────────────────────────────────────────────
	{ menuItemId: 'sides-lettuce',                         name: 'Lettuce',                   category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-perilla-leaves-kkaennip',         name: 'Perilla Leaves (Kkaennip)', category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-garlic-whole-cloves',             name: 'Garlic (Whole Cloves)',     category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-garlic-sliced',                   name: 'Garlic (Sliced)',           category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-green-onions-scallions',          name: 'Green Onions / Scallions',  category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-jalape-o-green-chilies',          name: 'Jalapeño / Green Chilies',  category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-white-yellow-onions',             name: 'White/Yellow Onions',       category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-korean-radish-mu',                name: 'Korean Radish (Mu)',        category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-enoki-mushrooms',                 name: 'Enoki Mushrooms',           category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-button-mushrooms',                name: 'Button Mushrooms',          category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-corn',                            name: 'Corn',                      category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-baguio-pechay',                   name: 'Baguio Pechay',             category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-squash',                          name: 'Squash',                    category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-baechu-kimchi',                   name: 'Baechu Kimchi',             category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-kkakdugi',                        name: 'Kkakdugi',                  category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-kongnamul-muchim',                name: 'Kongnamul-muchim',          category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-oi-muchim',                       name: 'Oi Muchim',                 category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-pickled-white-onions',            name: 'Pickled White Onions',      category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-pickled-daikon-radish',           name: 'Pickled Daikon Radish',     category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-eomuk-bokkeum',                   name: 'Eomuk Bokkeum',             category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-japchae',                         name: 'Japchae',                   category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-gamja-jorim',                     name: 'Gamja Jorim',               category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-gyeran-jjim',                     name: 'Gyeran-jjim',               category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-pajeon',                          name: 'Pajeon',                    category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-gamja-salad',                     name: 'Gamja Salad',               category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-cheesy-tteokbokki',               name: 'Cheesy Tteokbokki',         category: 'Sides',     locationId: 'mkti',    unit: 'portions',   minLevel: 20     },
	{ menuItemId: 'sides-gochujang',                       name: 'Gochujang',                 category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-doenjang',                        name: 'Doenjang',                  category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-gochugaru-coarse',                name: 'Gochugaru (Coarse)',        category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-gochugaru-fine',                  name: 'Gochugaru (Fine)',          category: 'Sides',     locationId: 'mkti',    unit: 'g',          minLevel: 2000   },
	{ menuItemId: 'sides-jin-ganjang-dark-soy-sauce',      name: 'Jin-ganjang (Dark Soy Sauce)', category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-guk-ganjang-soup-soy-sauce',      name: 'Guk-ganjang (Soup Soy Sauce)', category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-yangjo-ganjang-brewed-soy',       name: 'Yangjo-ganjang (Brewed Soy)', category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-toasted-sesame-oil',              name: 'Toasted Sesame Oil',        category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-mulyeot-corn-rice-syrup',         name: 'Mulyeot (Corn/Rice Syrup)', category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-mirin-rice-wine',                 name: 'Mirin / Rice Wine',         category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-aekjeot-fish-sauce',              name: 'Aekjeot (Fish Sauce)',      category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-dasida-beef-stock-powder',        name: 'Dasida (Beef Stock Powder)', category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-mayonnaise',                      name: 'Mayonnaise',                category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 2000   },
	{ menuItemId: 'sides-ssamjang',                        name: 'Ssamjang',                  category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 1000   },
	{ menuItemId: 'sides-sogeumjang',                      name: 'Sogeumjang',                category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 1000   },
	{ menuItemId: 'sides-cheese-sauce',                    name: 'Cheese Sauce',              category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 1000   },
	{ menuItemId: 'sides-wasabi-soy',                      name: 'Wasabi Soy',                category: 'Sides',     locationId: 'mkti',    unit: 'ml',         minLevel: 1000   },
	{ menuItemId: 'drinks-original-soju',                  name: 'Original Soju',             category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-flavored-soju-grapefruit',       name: 'Flavored Soju - Grapefruit', category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-flavored-soju-green-grape',      name: 'Flavored Soju - Green Grape', category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-flavored-soju-plum',             name: 'Flavored Soju - Plum',      category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-flavored-soju-strawberry',       name: 'Flavored Soju - Strawberry', category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-makgeolli',                      name: 'Makgeolli',                 category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-san-miguel-pilsen',              name: 'San Miguel Pilsen',         category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-san-miguel-light',               name: 'San Miguel Light',          category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-red-horse',                      name: 'Red Horse',                 category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-cass',                           name: 'Cass',                      category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-hite',                           name: 'Hite',                      category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-ob',                             name: 'OB',                        category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-taedonggang',                    name: 'Taedonggang',               category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-coca-cola',                      name: 'Coca-Cola',                 category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-sprite',                         name: 'Sprite',                    category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-coke-zero',                      name: 'Coke Zero',                 category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-chilsung-cider',                 name: 'Chilsung Cider',            category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-iced-red-tea',                   name: 'Iced Red Tea',              category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-barley-tea-boricha',             name: 'Barley Tea (Boricha)',      category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },
	{ menuItemId: 'drinks-lemonade',                       name: 'Lemonade',                  category: 'Drinks',    locationId: 'mkti',    unit: 'bottles',    minLevel: 24     },

	// ── Central Warehouse Stock ───────────────────────────────────────────────
	{ menuItemId: 'meat-pork-bone-in',   name: 'Pork Bone-In (Bulk)',        category: 'Meats', proteinType: 'pork', locationId: 'wh-qc', unit: 'g',        minLevel: 20000 },
	{ menuItemId: 'meat-pork-bone-out',  name: 'Pork Bone-Out (Bulk)',       category: 'Meats', proteinType: 'pork', locationId: 'wh-qc', unit: 'g',        minLevel: 20000 },
	{ menuItemId: 'meat-pork-sliced',    name: 'Sliced Pork (Bulk)',         category: 'Meats', proteinType: 'pork', locationId: 'wh-qc', unit: 'g',        minLevel: 20000 },
	{ menuItemId: 'meat-pork-bones',     name: 'Pork Bones (Bulk)',          category: 'Meats', proteinType: 'pork', locationId: 'wh-qc', unit: 'g',        minLevel: 10000 },
	{ menuItemId: 'meat-pork-trimmings', name: 'Pork Trimmings (Bulk)',      category: 'Meats', proteinType: 'pork', locationId: 'wh-qc', unit: 'g',        minLevel: 5000  },
	{ menuItemId: 'meat-beef-bone-in',   name: 'Beef Bone-In (Bulk)',        category: 'Meats', proteinType: 'beef', locationId: 'wh-qc', unit: 'g',        minLevel: 15000 },
	{ menuItemId: 'meat-beef-bone-out',  name: 'Beef Bone-Out (Bulk)',       category: 'Meats', proteinType: 'beef', locationId: 'wh-qc', unit: 'g',        minLevel: 15000 },
	{ menuItemId: 'meat-beef-sliced',    name: 'Sliced Beef (Bulk)',         category: 'Meats', proteinType: 'beef', locationId: 'wh-qc', unit: 'g',        minLevel: 15000 },
	{ menuItemId: 'meat-beef-bones',     name: 'Beef Bones (Bulk)',          category: 'Meats', proteinType: 'beef', locationId: 'wh-qc', unit: 'g',        minLevel: 10000 },
	{ menuItemId: 'meat-beef-trimmings', name: 'Beef Trimmings (Bulk)',      category: 'Meats', proteinType: 'beef', locationId: 'wh-qc', unit: 'g',        minLevel: 5000  },
	{ menuItemId: 'meat-chicken-wing',   name: 'Chicken Wing (Bulk)',        category: 'Meats', proteinType: 'chicken', locationId: 'wh-qc', unit: 'g',        minLevel: 10000 },
	{ menuItemId: 'meat-chicken-leg',    name: 'Chicken Leg (Bulk)',         category: 'Meats', proteinType: 'chicken', locationId: 'wh-qc', unit: 'g',        minLevel: 10000 },
	{ menuItemId: 'side-noodles',        name: 'Dangmyeon Bulk',             category: 'Sides',  locationId: 'wh-qc', unit: 'portions', minLevel: 50    },

	// ── Additional Warehouse stock ────────────────────────────────────────────
	{ menuItemId: 'sides-lettuce',                         name: 'Lettuce',                   category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-perilla-leaves-kkaennip',         name: 'Perilla Leaves (Kkaennip)', category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-garlic-whole-cloves',             name: 'Garlic (Whole Cloves)',     category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-garlic-sliced',                   name: 'Garlic (Sliced)',           category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-green-onions-scallions',          name: 'Green Onions / Scallions',  category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-jalape-o-green-chilies',          name: 'Jalapeño / Green Chilies',  category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-white-yellow-onions',             name: 'White/Yellow Onions',       category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-korean-radish-mu',                name: 'Korean Radish (Mu)',        category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-enoki-mushrooms',                 name: 'Enoki Mushrooms',           category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-button-mushrooms',                name: 'Button Mushrooms',          category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-corn',                            name: 'Corn',                      category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-baguio-pechay',                   name: 'Baguio Pechay',             category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-squash',                          name: 'Squash',                    category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-baechu-kimchi',                   name: 'Baechu Kimchi',             category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-kkakdugi',                        name: 'Kkakdugi',                  category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-kongnamul-muchim',                name: 'Kongnamul-muchim',          category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-oi-muchim',                       name: 'Oi Muchim',                 category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-pickled-white-onions',            name: 'Pickled White Onions',      category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-pickled-daikon-radish',           name: 'Pickled Daikon Radish',     category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-eomuk-bokkeum',                   name: 'Eomuk Bokkeum',             category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-japchae',                         name: 'Japchae',                   category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-gamja-jorim',                     name: 'Gamja Jorim',               category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-gyeran-jjim',                     name: 'Gyeran-jjim',               category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-pajeon',                          name: 'Pajeon',                    category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-gamja-salad',                     name: 'Gamja Salad',               category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-cheesy-tteokbokki',               name: 'Cheesy Tteokbokki',         category: 'Sides',     locationId: 'wh-qc',   unit: 'portions',   minLevel: 80     },
	{ menuItemId: 'sides-gochujang',                       name: 'Gochujang',                 category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-doenjang',                        name: 'Doenjang',                  category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-gochugaru-coarse',                name: 'Gochugaru (Coarse)',        category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-gochugaru-fine',                  name: 'Gochugaru (Fine)',          category: 'Sides',     locationId: 'wh-qc',   unit: 'g',          minLevel: 8000   },
	{ menuItemId: 'sides-jin-ganjang-dark-soy-sauce',      name: 'Jin-ganjang (Dark Soy Sauce)', category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 8000   },
	{ menuItemId: 'sides-guk-ganjang-soup-soy-sauce',      name: 'Guk-ganjang (Soup Soy Sauce)', category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 8000   },
	{ menuItemId: 'sides-yangjo-ganjang-brewed-soy',       name: 'Yangjo-ganjang (Brewed Soy)', category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 8000   },
	{ menuItemId: 'sides-toasted-sesame-oil',              name: 'Toasted Sesame Oil',        category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 8000   },
	{ menuItemId: 'sides-mulyeot-corn-rice-syrup',         name: 'Mulyeot (Corn/Rice Syrup)', category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 8000   },
	{ menuItemId: 'sides-mirin-rice-wine',                 name: 'Mirin / Rice Wine',         category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 8000   },
	{ menuItemId: 'sides-aekjeot-fish-sauce',              name: 'Aekjeot (Fish Sauce)',      category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 8000   },
	{ menuItemId: 'sides-dasida-beef-stock-powder',        name: 'Dasida (Beef Stock Powder)', category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 8000   },
	{ menuItemId: 'sides-mayonnaise',                      name: 'Mayonnaise',                category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 8000   },
	{ menuItemId: 'sides-ssamjang',                        name: 'Ssamjang',                  category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 4000   },
	{ menuItemId: 'sides-sogeumjang',                      name: 'Sogeumjang',                category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 4000   },
	{ menuItemId: 'sides-cheese-sauce',                    name: 'Cheese Sauce',              category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 4000   },
	{ menuItemId: 'sides-wasabi-soy',                      name: 'Wasabi Soy',                category: 'Sides',     locationId: 'wh-qc',   unit: 'ml',         minLevel: 4000   },
	{ menuItemId: 'drinks-original-soju',                  name: 'Original Soju',             category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-flavored-soju-grapefruit',       name: 'Flavored Soju - Grapefruit', category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-flavored-soju-green-grape',      name: 'Flavored Soju - Green Grape', category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-flavored-soju-plum',             name: 'Flavored Soju - Plum',      category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-flavored-soju-strawberry',       name: 'Flavored Soju - Strawberry', category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-makgeolli',                      name: 'Makgeolli',                 category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-san-miguel-pilsen',              name: 'San Miguel Pilsen',         category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-san-miguel-light',               name: 'San Miguel Light',          category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-red-horse',                      name: 'Red Horse',                 category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-cass',                           name: 'Cass',                      category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-hite',                           name: 'Hite',                      category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-ob',                             name: 'OB',                        category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-taedonggang',                    name: 'Taedonggang',               category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-coca-cola',                      name: 'Coca-Cola',                 category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-sprite',                         name: 'Sprite',                    category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-coke-zero',                      name: 'Coke Zero',                 category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-chilsung-cider',                 name: 'Chilsung Cider',            category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-iced-red-tea',                   name: 'Iced Red Tea',              category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-barley-tea-boricha',             name: 'Barley Tea (Boricha)',      category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
	{ menuItemId: 'drinks-lemonade',                       name: 'Lemonade',                  category: 'Drinks',    locationId: 'wh-qc',   unit: 'bottles',    minLevel: 96     },
];
